---
cloud:
  id: "dev-aic-ob-private-id"
  key: "dev-aic-ob-private-key"

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  cloudType: "CDK"
  projectId: "example-project"
  sapigType: "ob"

externalCert:
  fapiPepAs:
    mtlsCertPrefix: "dev-as-mtls"
    mtlsSecretName: "fapi-pep-as-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-as-tls-cert"
  fapiPepRs:
    mtlsCertPrefix: "dev-rs-mtls"
    mtlsSecretName: "fapi-pep-rs-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-rs-tls-cert"
  ob:
    signingKey:
      googleSecretName: "dev-ig-ob-signing-key"
  sampleTrustedDirectory:
    mtlscaSecretName: "sample-trusted-directory-mtls-ca-certs"
    mtlscaGoogleSecretName: "sample-trusted-directory-mtls-ca-certs"
    tlsSecretName: "sample-trusted-directory-tls-cert"
    tlsCertPrefix: "dev"
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: "am-oauth2-ca-certs"

fapiPepAs:
  repoURL: "https://github.com/ping-rocks/openig.git"
  branch: "HEAD"
  authorizationServer:
    realm: "alpha"
    fqdn: "as-sapig.dev-cdk-ob.forgerock.financial"
    mtlsFqdn: "as-mtls.sapig.dev-cdk-ob.forgerock.financial"
    baseFqdn: "dev-cdk-ob.forgerock.financial"
  identityPlatform:
    type: "CDK"
    fqdn: "iam.dev-cdk-ob.forgerock.financial"
    googleSecretStoreProject: "sbat-gcr-develop"
  aic:
    identityDefaultUserAuthenticationService: "PasswordGrant"
    identityGoogleSecretStoreName: "ESV"
    identityGoogleSecretStoreOAuth2CACertsSecretName: "esv-sapig-ob-am-oauth2-ca-certs"
  pingGateway:
    oauth2Client:
      id: "aWctY2xpZW50"
      secret: "cGFzc3dvcmQ="
    idm:
      user: "c2VydmljZV9hY2NvdW50Lmln"
      password: "MHBlbkJhbmtpbmch"
  deployment:
    image:
      repo: "gcr.io/forgerock-io/ig-fapi-pep-as/docker-build"
      tag: "latest"

fapiPepRs:
  branch: "HEAD"
  authorizationServer:
    realm: "alpha"
    fqdn: "as-sapig.dev-cdk-ob.forgerock.financial"
    baseFqdn: "dev-cdk-ob.forgerock.financial"
  identityPlatform:
    fqdn: "iam.dev-cdk-ob.forgerock.financial"
    type: "CDK"
  resourceServer:
    fqdn: "rs-sapig.dev-cdk-ob.forgerock.financial"
    mtlsFqdn: "rs-mtls.sapig.dev-cdk-ob.forgerock.financial"
    oauth2Client:
      id: "aWctY2xpZW50"
      secret: "cGFzc3dvcmQ="
    idm:
      user: "c2VydmljZV9hY2NvdW50Lmln"
      password: "MHBlbkJhbmtpbmch"
    agent:
      id: "aWctYWdlbnQ="
      password: "cGFzc3dvcmQ="
    ob:
      signingKeystore:
        kid: "zBlb3x2klab0COMzC5ROYxNo8n4"
        storepass: "cGFzc3dvcmQ="
        keypass: "cGFzc3dvcmQ="
  mongodb:
    testFacility:
      username: "dGVzdC1mYWNpbGl0eS1iYW5r"
      password: "UlZkYjdZdlg5NjdR"
    consent:
      username: "Y29uc2VudA=="
      password: "TDNoNXd4czRkRnZW"
  aic:
    identityDefaultUserAuthenticationService: "PasswordGrant"
    identityGoogleSecretStoreName: "ESV"
    identityGoogleSecretStoreOAuth2CACertsSecretName: "esv-sapig-ob-am-oauth2-ca-certs"
  deployment:
    image:
      repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/fapi-pep-rs-ob"
      tag: "latest"
  ingress:
    mtls:
      serverCertSecret: "fapi-pep-rs-mtls-tls-cert"
      clientCaSecret: "fapi-pep-rs-mtls-ca-certs"
    tls:
      serverCertSecret: "fapi-pep-rs-tls-cert"

fidcConfigurator:
  enabled: "true"
  branch: "HEAD"
  asDeploymentConfigMap: "ig-fapi-pep-as-config"
  asSecret: "ig-fapi-pep-as-secrets"
  rsDeploymentConfigMap: "fapi-pep-rs-ob-config"
  rsObSecret: "fapi-pep-rs-ob-secrets"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/secureopenbanking-uk-iam-initializer"
    tag: "latest"

remoteConsentServer:
  branch: "HEAD"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-openbanking-uk-rcs"
    tag: "latest"

remoteConsentServiceUserInterface:
  branch: "HEAD"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/ui/rcs"
    tag: "latest"

spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "dev"
  source:
    targetRevision: "HEAD"
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

testFacilityBank:
  branch: "HEAD"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-openbanking-uk-rs"
    tag: "latest"

sampleTrustedDirectory:
  branch: "HEAD"
  config:
    fqdn: "test-trusted-directory.dev-cdk-ob.forgerock.financial"
    ca:
      keystoreKeyPwd: "UGFzc3cwcmQ="
      keystorePwd: "UGFzc3cwcmQ="
    signing:
      keystoreKeyPwd: "UGFzc3cwcmQ="
      keystorePwd: "UGFzc3cwcmQ="
  deployment:
    image:
      repo: "gcr.io/forgerock-io/ig-sample-trusted-directory/docker-build"
      tag: "latest"
  ingress:
    host: "test-trusted-directory.dev-cdk-ob.forgerock.financial"
    tls:

testUserAccountCreator:
  branch: "HEAD"
  asDeploymentConfigMap: "ig-fapi-pep-as-config"
  deployment:
    type: "CronJob"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-test-data-initializer"
    tag: "latest"