apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ig-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlay/7.0/obdemo-bank/{{ .Values.spec.destination.namespace }}
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo
    targetRevision: {{ .Values.ig.branch }}
    kustomize:
      images:
        - 'ig=eu.gcr.io/sbat-gcr-develop/securebanking/gate/ig:{{ .Values.ig.tag }}'
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}