apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: mongodb
    helm:
      parameters:
      - name: auth.usernames
        value: {{- range .Values.mongodb.auth.usernames }}{{.}}{{- end }}
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.6.1
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
