apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: rcsUI.deployment.imageOverride.tag
        value: {{ .Values.ui.tag }}
      - name: rcsUI.deployment.templateName
        value: {{ .Values.ui.templateName }}
    path: _infra/helm/securebanking-ui
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-ui
    targetRevision: {{ .Values.ui.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
