apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: ingress.domain
        value: {{ .Values.ingress.domain }}
      - name: rcsUI.deployment.imageOverride.tag
        value: {{ .Values.ui.tag }}
      - name: swaggerUI.deployment.imageOverride.tag
        value: {{ .Values.ui.tag }}
      - name: swaggerUI.deployment.templateName
        value: {{ .Values.ui.templateName }}
      - name: rcsUI.deployment.templateName
        value: {{ .Values.ui.templateName }}
      - name: deployment.urls.authorization.server
        value: {{ .Values.urls.authorization.server }}
      - name: deployment.urls.rcs.server
        value: {{ .Values.urls.rcs.server }}
      - name: deployment.urls.ig.server
        value: {{ .Values.urls.ig.server}}
    path: _infra/helm/securebanking-ui
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-ui
    targetRevision: {{ .Values.ui.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
