apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fapi-pep-as-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # ConfigMap
        - name: fapiPepAs.configmap.amRealm
          value: {{ .Values.fapiPepAs.configmap.amRealm }}
        - name: fapiPepAs.configmap.baseFQDN
          value: {{ .Values.fapiPepAs.configmap.baseFQDN }}
        - name: fapiPepAs.configmap.cloudType
          value: {{ .Values.fapiPepAs.configmap.cloudType }}
        - name: fapiPepAs.configmap.identityPlatformFQDN
          value: {{ .Values.fapiPepAs.configmap.identityPlatformFQDN }}
        - name: fapiPepAs.configmap.asFQDN
          value: {{ .Values.fapiPepAs.configmap.asFQDN }}
        - name: fapiPepAs.configmap.asMtlsFQDN
          value: {{ .Values.fapiPepAs.configmap.asMtlsFQDN }}
        - name: fapiPepAs.configmap.sapigType
          value: {{ .Values.fapiPepAs.configmap.sapigType }}
        - name: fapiPepAs.configmap.testDirectoryFQDN
          value: {{ .Values.fapiPepAs.configmap.testDirectoryFQDN }}
        - name: fapiPepAs.configmap.userObject
          value: {{ .Values.fapiPepAs.configmap.userObject }}
        - name: fapiPepAs.configmap.AIC.identityDefaultUserAuthenticationService
          value: {{ .Values.fapiPepAs.configmap.identityDefaultUserAuthenticationService }}
        - name: fapiPepAs.configmap.AIC.identityGoogleSecretStoreName
          value: {{ .Values.fapiPepAs.configmap.identityGoogleSecretStoreName }}
        - name: fapiPepAs.configmap.AIC.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.fapiPepAs.configmap.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: fapiPepAs.deployment.image.repo
          value: {{ .Values.fapiPepAs.deployment.repo}}
        - name: fapiPepAs.deployment.image.tag
          value: {{ .Values.fapiPepAs.deployment.tag }}
        # Ingress
        - name: fapiPepAs.ingress.asSapig.host
          value: {{ .Values.fapiPepAs.ingress.asSapig.host }}
        - name: fapiPepAs.ingress.asSapig.tls.host
          value: {{ .Values.fapiPepAs.ingress.asSapig.tls.host }}
        - name: fapiPepAs.ingress.asMtls.host
          value: {{ .Values.fapiPepAs.ingress.asMtls.host }}
        - name: fapiPepAs.ingress.asMtls.tls.host
          value: {{ .Values.fapiPepAs.ingress.asMtls.tls.host }}
        - name: fapiPepAs.ingress.asIGSstudio.host
          value: {{ .Values.fapiPepAs.ingress.asIGSstudio.host }}
        - name: fapiPepAs.ingress.asIGSstudio.tls.host
          value: {{ .Values.fapiPepAs.ingress.asIGSstudio.tls.host }}
        # Secrets
        - name: fapiPepAs.secrets.igAgentID
          value: {{ .Values.fapiPepAs.secrets.igAgentID }}
        - name: fapiPepAs.secrets.igAgentPassword
          value: {{ .Values.fapiPepAs.secrets.igAgentPassword }}
        - name: fapiPepAs.secrets.igClientID
          value: {{ .Values.fapiPepAs.secrets.igClientID }}
        - name: fapiPepAs.secrets.igClientSecret
          value: {{ .Values.fapiPepAs.secrets.igClientSecret }}
        - name: fapiPepAs.secrets.igIDMPassword
          value: {{ .Values.fapiPepAs.secrets.igIDMPassword }}
        - name: fapiPepAs.secrets.igIDMUser
          value: {{ .Values.fapiPepAs.secrets.igIDMUser }}
        - name: fapiPepAs.secrets.igMetricsPassword
          value: {{ .Values.fapiPepAs.secrets.igMetricsPassword }}
        - name: fapiPepAs.secrets.igMetricsUsername
          value: {{ .Values.fapiPepAs.secrets.igMetricsUsername }}
        - name: fapiPepAs.secrets.igTruststorePassword
          value: {{ .Values.fapiPepAs.secrets.igTruststorePassword }}
    path: _infra/helm/secure-api-gateway-fapi-pep-as
    repoURL: https://github.com/SecureApiGateway/secure-api-gateway-fapi-pep-as
    targetRevision: {{ .Values.fapiPepAs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
