apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fapi-pep-rs-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # ConfigMap
        - name: fapiPepRs.configmap.amRealm
          value: {{ .Values.fapiPepRs.configmap.amRealm }}
        - name: fapiPepRs.configmap.baseFQDN
          value: {{ .Values.fapiPepRs.configmap.baseFQDN }}
        - name: fapiPepRs.configmap.cloudType
          value: {{ .Values.fapiPepRs.configmap.cloudType }}
        - name: fapiPepRs.configmap.identityPlatformFQDN
          value: {{ .Values.fapiPepRs.configmap.identityPlatformFQDN }}
        - name: fapiPepRs.configmap.asFQDN
          value: {{ .Values.fapiPepRs.configmap.asFQDN }}
        - name: fapiPepRs.configmap.rsFQDN
          value: {{ .Values.fapiPepRs.configmap.rsFQDN }}
        - name: fapiPepRs.configmap.rsMtlsFQDN
          value: {{ .Values.fapiPepRs.configmap.rsMtlsFQDN }}
        - name: fapiPepRs.configmap.sapigType
          value: {{ .Values.fapiPepRs.configmap.sapigType }}
        - name: fapiPepRs.configmap.testDirectoryFQDN
          value: {{ .Values.fapiPepRs.configmap.testDirectoryFQDN }}
        - name: fapiPepRs.configmap.userObject
          value: {{ .Values.fapiPepRs.configmap.userObject }}
        - name: fapiPepRs.configmap.AIC.identityDefaultUserAuthenticationService
          value: {{ .Values.fapiPepRs.configmap.identityDefaultUserAuthenticationService }}
        - name: fapiPepRs.configmap.AIC.identityGoogleSecretStoreName
          value: {{ .Values.fapiPepRs.configmap.identityGoogleSecretStoreName }}
        - name: fapiPepRs.configmap.AIC.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.fapiPepRs.configmap.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: fapiPepRs.deployment.image.repo
          value: {{ .Values.fapiPepRs.deployment.repo}}
        - name: fapiPepRs.deployment.image.tag
          value: {{ .Values.fapiPepRs.deployment.tag }}
        # Ingress
        - name: fapiPepRs.ingress.rsSapig.host
          value: {{ .Values.fapiPepRs.ingress.rsSapig.host }}
        - name: fapiPepRs.ingress.rsSapig.tls.host
          value: {{ .Values.fapiPepRs.ingress.rsSapig.tls.host }}
        - name: fapiPepRs.ingress.rsMtls.host
          value: {{ .Values.fapiPepRs.ingress.rsMtls.host }}
        - name: fapiPepRs.ingress.rsMtls.tls.host
          value: {{ .Values.fapiPepRs.ingress.rsMtls.tls.host }}
        - name: fapiPepRs.ingress.rsIGSstudio.host
          value: {{ .Values.fapiPepRs.ingress.rsIGSstudio.host }}
        - name: fapiPepRs.ingress.rsIGSstudio.tls.host
          value: {{ .Values.fapiPepRs.ingress.rsIGSstudio.tls.host }}
        # Secrets
        - name: fapiPepRs.secrets.igAgentID
          value: {{ .Values.fapiPepRs.secrets.igAgentID }}
        - name: fapiPepRs.secrets.igAgentPassword
          value: {{ .Values.fapiPepRs.secrets.igAgentPassword }}
        - name: fapiPepRs.secrets.igClientID
          value: {{ .Values.fapiPepRs.secrets.igClientID }}
        - name: fapiPepRs.secrets.igClientSecret
          value: {{ .Values.fapiPepRs.secrets.igClientSecret }}
        - name: fapiPepRs.secrets.igIDMPassword
          value: {{ .Values.fapiPepRs.secrets.igIDMPassword }}
        - name: fapiPepRs.secrets.igIDMUser
          value: {{ .Values.fapiPepRs.secrets.igIDMUser }}
        - name: fapiPepRs.secrets.igMetricsPassword
          value: {{ .Values.fapiPepRs.secrets.igMetricsPassword }}
        - name: fapiPepRs.secrets.igMetricsUsername
          value: {{ .Values.fapiPepRs.secrets.igMetricsUsername }}
        - name: fapiPepRs.secrets.igTruststorePassword
          value: {{ .Values.fapiPepRs.secrets.igTruststorePassword }}
    path: _infra/helm/secure-api-gateway-fapi-pep-rs-core
    repoURL: https://github.com/SecureApiGateway/secure-api-gateway-fapi-pep-rs-core
    targetRevision: {{ .Values.fapiPepRs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
