apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fapi-pep-rs-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # Authorization Server
        - name: authorizationServer.realm
          value: {{ .Values.fapiPepRs.authorizationServer.realm }}
        - name: authorizationServer.fqdn
          value: {{ .Values.fapiPepRs.authorizationServer.fqdn }}
        - name: authorizationServer.baseFqdn
          value: {{ .Values.fapiPepRs.authorizationServer.baseFqdn }}
        # Identity Platform
        - name: identityPlatform.fqdn
          value: {{ .Values.fapiPepRs.identityPlatform.fqdn }}
        - name: identityPlatform.type
          value: {{ .Values.fapiPepRs.identityPlatform.type }}
        - name: identityPlatform.userObject
          value: {{ .Values.fapiPepRs.identityPlatform.userObject }}
        # Resource Server
        - name: resourceServer.fqdn
          value: {{ .Values.fapiPepRs.resourceServer.fqdn }}
        - name: resourceServer.mtlsFqdn
          value: {{ .Values.fapiPepRs.resourceServer.mtlsFqdn }}
        - name: resourceServer.gatewayDataRepoUri
          value: {{ .Values.fapiPepRs.resourceServer.gatewayDataRepoUri }}
        - name: resourceServer.oauth2Client.id
          value: {{ .Values.fapiPepRs.resourceServer.oauth2Client.id }}
        - name: resourceServer.oauth2Client.secret
          value: {{ .Values.fapiPepRs.resourceServer.oauth2Client.secret }}
        - name: resourceServer.idm.user
          value: {{ .Values.fapiPepRs.resourceServer.idm.user }}
        - name: resourceServer.idm.password
          value: {{ .Values.fapiPepRs.resourceServer.idm.password }}
        # AIC
        - name: aic.identityDefaultUserAuthenticationService
          value: {{ .Values.fapiPepRs.aic.identityDefaultUserAuthenticationService }}
        - name: aic.identityGoogleSecretStoreName
          value: {{ .Values.fapiPepRs.aic.identityGoogleSecretStoreName }}
        - name: aic.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.fapiPepRs.aic.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: deployment.image.repo
          value: {{ .Values.fapiPepRs.deployment.image.repo }}
        - name: deployment.image.tag
          value: {{ .Values.fapiPepRs.deployment.image.tag }}
        # Ingress
        - name: ingress.mtls.serverCertSecret
          value: {{ .Values.fapiPepRs.ingress.mtls.serverCertSecret }}
        - name: ingress.mtls.clientCaSecret
          value: {{ .Values.fapiPepRs.ingress.mtls.clientCaSecret }}
        - name: ingress.tls.serverCertSecret
          value: {{ .Values.fapiPepRs.ingress.tls.serverCertSecret }}
    path: openig-helm/ig-fapi-pep-rs
    repoURL: {{ .Values.fapiPepRs.repoURL }}
    targetRevision: {{ .Values.fapiPepRs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
