apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-trusted-directory-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # ConfigMap
        - name: testTrustedDirectory.configmap.igTestDirectoryFQDN
          value: {{ .Values.testTrustedDirectory.configmap.igTestDirectoryFQDN }}
        # Deployment
        - name: testTrustedDirectory.deployment.image.repo
          value: {{ .Values.testTrustedDirectory.deployment.repo}}
        - name: testTrustedDirectory.deployment.image.tag
          value: {{ .Values.testTrustedDirectory.deployment.tag }}
        # Ingress
        - name: testTrustedDirectory.ingress.host
          value: {{ .Values.testTrustedDirectory.ingress.host }}
        - name: testTrustedDirectory.ingress.tls.host
          value: {{ .Values.testTrustedDirectory.ingress.tls.host }}
        # Secrets
        - name: testTrustedDirectory.secrets.igMetricsPassword
          value: {{ .Values.testTrustedDirectory.secrets.igMetricsPassword }}
        - name: testTrustedDirectory.secrets.igMetricsUsername
          value: {{ .Values.testTrustedDirectory.secrets.igMetricsUsername }}
        - name: testTrustedDirectory.secrets.igTestDirectoryCAKeystoreKeypass
          value: {{ .Values.testTrustedDirectory.secrets.igTestDirectoryCAKeystoreKeypass }}
        - name: testTrustedDirectory.secrets.igTestDirectoryCAKeystoreStorepass
          value: {{ .Values.testTrustedDirectory.secrets.igTestDirectoryCAKeystoreStorepass }}
        - name: testTrustedDirectory.secrets.igTestDirectorySigningKeystoreKeypass
          value: {{ .Values.testTrustedDirectory.secrets.igTestDirectorySigningKeystoreKeypass }}
        - name: testTrustedDirectory.secrets.igTestDirectorySigningKeystoreStorepass
          value: {{ .Values.testTrustedDirectory.secrets.igTestDirectorySigningKeystoreStorepass }}
    path: _infra/helm/secure-api-gateway-test-trusted-directory
    repoURL: https://github.com/SecureApiGateway/secure-api-gateway-test-trusted-directory
    targetRevision: {{ .Values.testTrustedDirectory.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
