# This initializer pod will be deployed in the namespace with the environment type = 'FIDC'
# Otherwise, currently this pod will be deployed in cdk namespace only
# @See the pipeline initialise, step 'install_initializer_cron_job'

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-user-account-creator-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: testUserAccountCreator.job.environment.cloudType
        value: {{ .Values.environment.cloudType }}
      - name: testUserAccountCreator.job.image.repo
        value: {{ .Values.testUserAccountCreator.repo}}
      - name: testUserAccountCreator.job.image.tag
        value: {{ .Values.testUserAccountCreator.tag }}
      - name: testUserAccountCreator.deployment.type
        value: {{ .Values.testUserAccountCreator.deployment.type }}
      - name: testUserAccountCreator.job.environment.sapigType
        value: core
    path: _infra/helm/securebanking-test-data-initializer
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-test-data-initializer
    targetRevision: {{ .Values.testUserAccountCreator.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
