apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-environment
spec:
  entrypoint: create-environment
  arguments:
    parameters:
      - name: clean
        value: false
      - name: namespace
        value: dev

  templates:
  - name: create-environment
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: clean
        template: clean
        arguments:
          parameters:
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
        when: "{{workflow.parameters.clean}}"
    - - name: init-namespace
        template: sync-git
        arguments:
          parameters:
          - name: application-name
            value: namespace-setup
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
    - - name: Mongodb
        template: sync-helm
        arguments:
          parameters:
          - name: application-name
            value: mongodb
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
      - name: securebanking-spring-config-server
        template: sync-git
        arguments:
          parameters:
          - name: application-name
            value: securebanking-spring-config-server
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
    - - name: securebanking-rs
        template: sync-git
        arguments:
          parameters:
          - name: application-name
            value: securebanking-rs
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
    - - name: securebanking-rcs
        template: sync-git
        arguments:
          parameters:
          - name: application-name
            value: securebanking-rcs
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
  
  - name: clean
    inputs:
      parameters:
      - name: namespace
    container:
      image: eu.gcr.io/sbat-gcr-develop/ci/gcloud-tools:latest
      command: [ /bin/bash, -c ]
      args:
        - |
          kubectl delete ns "{{inputs.parameters.namespace}}" --ignore-not-found --wait --force

  - name: sync-git
    inputs:
      parameters:
      - name: application-name
      - name: namespace
    steps:                              # You should only reference external "templates" in a "steps" or "dag" "template".
      - - name: sync
          templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
            name: argocd-sync-and-wait   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
            template: sync-git # This is the name of the "template" you want to reference
          arguments:                    # You can pass in arguments as normal
            parameters:
            - name: application-name
              value: "{{inputs.parameters.application-name}}"
            - name: namespace
              value: "{{inputs.parameters.namespace}}"
  
  - name: sync-helm
    inputs:
      parameters:
      - name: application-name
      - name: namespace
    steps:                              # You should only reference external "templates" in a "steps" or "dag" "template".
      - - name: sync
          templateRef:                  # You can reference a "template" from another "WorkflowTemplate or ClusterWorkflowTemplate" using this field
            name: argocd-sync-and-wait   # This is the name of the "WorkflowTemplate or ClusterWorkflowTemplate" CRD that contains the "template" you want
            template: sync-helm  # This is the name of the "template" you want to reference
          arguments:                    # You can pass in arguments as normal
            parameters:
            - name: application-name
              value: "{{inputs.parameters.application-name}}"
            - name: namespace
              value: "{{inputs.parameters.namespace}}"