apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-environment
spec:
  entrypoint: create-environment
  arguments:
    parameters:
      - name: clean
        value: false
      - name: namespace
        value: dev

  templates:
  - name: create-environment
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: clean
        template: clean
        arguments:
          parameters:
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
        when: "{{workflow.parameters.clean}}"
    - - name: sync-parent-app
        template: sync-git
        arguments:
          parameters:
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
  
  - name: clean
    inputs:
      parameters:
      - name: namespace
    container:
      image: eu.gcr.io/sbat-gcr-develop/ci/gcloud-tools:latest
      command: [ /bin/bash, -c ]
      args:
        - |
          kubectl delete ns "{{inputs.parameters.namespace}}" --ignore-not-found --wait --force

  - name: sync-git
    inputs:
      parameters:
      - name: parent-name
        value: securebanking
      - name: namespace
    steps:
      - - name: sync
          templateRef:
            name: argocd-sync-and-wait
            template: sync-parent
          arguments:
            parameters:
            - name: parent-name
              value: "{{inputs.parameters.parent-name}}"
            - name: namespace
              value: "{{inputs.parameters.namespace}}"
  