apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: slack-rebuild-notify
  annotations:
    workflows.argoproj.io/description: >-
      Curl to the slack webhook url when an env has been created
    workflows.argoproj.io/tags: argocd
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  entrypoint: slack-notify
  arguments:
    parameters:
      - name: namespace
        value: dev
  templates:
  - name: slack-notify
    inputs:
      parameters:
      - name: namespace
        value: dev
    script:
      image: curlimages/curl:7.76.0
      command: [sh]
      env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: slack-webhook
              key: url
        - name: DOMAIN
          value: forgerock.financial
      source: |
        #!/bin/sh
        SLACK_MESSAGE=$(echo "sbat-dev environment building in the \`{{inputs.parameters.namespace}}\` namespace \n\n rs: \`rs.{{inputs.parameters.namespace}}.$DOMAIN\`\n rcs: \`rcs.{{inputs.parameters.namespace}}.$DOMAIN\`\n rcs-ui: \`rcs-ui.{{inputs.parameters.namespace}}.$DOMAIN\`\n auth-ui: \`auth.{{inputs.parameters.namespace}}.$DOMAIN\`\n swagger-ui: \`swagger.{{inputs.parameters.namespace}}.$DOMAIN\`")
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$SLACK_MESSAGE\"}" $SLACK_WEBHOOK_URL
