apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: argocd-sync-and-wait
  annotations:
    workflows.argoproj.io/description: >-
      This task syncs (deploys) an Argo CD application and waits for it to be healthy.

      To do so, it requires the address of the Argo CD server and
      authentication via username/password
    workflows.argoproj.io/tags: argocd
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  entrypoint: argocd-sync-and-wait
  templates:
  - name: sync-git
    inputs:
      parameters:
      - name: argocd-version
        value: v2.0.0
      - name: application-name
      - name: namespace
      - name: revision
        value: HEAD
      - name: flags
        value: --
    script:
      image: argoproj/argocd:{{inputs.parameters.argocd-version}}
      command: [bash]
      env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: argo-bot-token
              key: token
        - name: ARGOCD_SERVER
          valueFrom:
            configMapKeyRef:
              name: argocd-cm
              key: cli-server
      source: |
        #!/bin/bash

        set -euo pipefail

        argocd app sync {{inputs.parameters.application-name}}-{{inputs.parameters.namespace}} --revision {{inputs.parameters.revision}} {{inputs.parameters.flags}}
        argocd app wait {{inputs.parameters.application-name}}-{{inputs.parameters.namespace}} --health {{inputs.parameters.flags}}
  
  - name: sync-helm
    inputs:
      parameters:
      - name: argocd-version
        value: v2.0.0
      - name: application-name
      - name: namespace
      - name: flags
        value: --
    script:
      image: argoproj/argocd:{{inputs.parameters.argocd-version}}
      command: [bash]
      env:
        - name: ARGOCD_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: argo-bot-token
              key: token
        - name: ARGOCD_SERVER
          valueFrom:
            configMapKeyRef:
              name: argocd-cm
              key: cli-server
      source: |
        #!/bin/bash

        set -euo pipefail
        
        argocd app sync {{inputs.parameters.application-name}}-{{inputs.parameters.namespace}} {{inputs.parameters.flags}}
        argocd app wait {{inputs.parameters.application-name}}-{{inputs.parameters.namespace}} --health {{inputs.parameters.flags}}