---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalCert.fapiPepAs.tlsSecretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: {{ .Values.externalCert.fapiPepAs.tlsSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.externalCert.fapiPepAs.tlsCertPrefix }}-crt
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.externalCert.fapiPepAs.tlsCertPrefix }}-key
