---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalCert.fapiPepAs.mtlsCASecretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.externalCert.fapiPepAs.mtlsCASecretName }}
    creationPolicy: Owner
  data:
  - secretKey: ca.crt
    remoteRef:
      key: {{ .Values.externalCert.fapiPepAs.mtlsCAGoogleSecretName }}
