apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.testTrustedDirectory.secretName }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.externalCert.projectId }}
  data:
    - key: {{ .Values.ig.testTrustedDirectory.googleSecretName }}
      name: {{ .Values.ig.testTrustedDirectory.fileName }}
      version: latest
      isBinary: true