apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.truststore.secretName }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.externalCert.projectId }}
  data:
    - key: {{ .Values.ig.truststore.googleSecretName }}
      name: {{ .Values.ig.truststore.fileName }}
      version: latest
