apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.testTrustedDirectory.secretName }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.externalCert.projectId }}
  data:
    - key: {{ .Values.ig.testTrustedDirectory.ca.googleSecretName }}
      name: {{ .Values.ig.testTrustedDirectory.ca.fileName }}
      version: latest
    - key: { { .Values.ig.testTrustedDirectory.signingKey.googleSecretName } }
      name: { { .Values.ig.testTrustedDirectory.signingKey.fileName } }
      version: latest
