---
{{- if eq .Values.environment.sapigType "ob" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalCert.ob.mtlsSecretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: {{ .Values.externalCert.ob.mtlsSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: tls.crt
    remoteRef:
      key: {{ .Values.externalCert.ob.mtlsCertPrefix }}-crt
  - secretKey: tls.key
    remoteRef:
      key: {{ .Values.externalCert.ob.mtlsCertPrefix }}-key
{{ end }}