---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalCert.ob.mtlsCASecretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.externalCert.ob.mtlsCASecretName }}
    creationPolicy: Owner
  data:
  - secretKey: ca.crt
    remoteRef:
      key: {{ .Values.externalCert.ob.mtlsCAGoogleSecretName }}
