apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.rcs.signing.secretName }}
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.externalCert.projectId }}
  data:
    - key: {{ .Values.rcs.signing.certPrefix }}-crt
      name: rcs-signing.pem
      version: latest
    - key: {{ .Values.rcs.signing.certPrefix }}-key
      name: rcs-signing.key
      version: latest