
serviceAccount: default

externalCert:
  projectId: example-project
  secretName: sslcert
  certPrefix: dev

openBankingCert:
  secretName: obwac
  certPrefix: ob-wac

ig:
  truststore:
    secretName: ig-truststore-pem
    fileName: ig-truststore.pem
    googleSecretName: ig-truststore-pem
  ob:
    signingKey:
      secretName: ig-ob-signing-key
      fileName: ig-ob-signing-key.p12
      googleSecretName: ig-ob-signing-key
  testTrustedDirectory:
    secretName: test-trusted-dir-keystore
    fileName: test-trusted-dir-keystore.p12
    googleSecretName: test-trusted-dir-keystore
rcs:
  signing:
    certPrefix: rcs-signing
    secretName: rcs-signing