cloud:
  id: "dev-aic-ob-private-id"
  key: "dev-aic-ob-private-key"

environment:
  sapigType: "ob"
  cloudType: "CDK"

serviceAccount: "default"

externalCert:
  projectId: "example-project"
  ob:
    mtlsCAGoogleSecretName: "ob-mtls-ca-certs"
    mtlsCASecretName: "ob-mtls-ca-certs"
    mtlsCertPrefix: "dev-ob-wac"
    mtlsSecretName: "ob-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "ob-tls-cert"
  fapiPepAs:
    mtlsCAGoogleSecretName: "fapi-pep-as-mtls-ca-certs"
    mtlsCASecretName: "fapi-pep-as-mtls-ca-certs"
    mtlsCertPrefix: "dev-as-mtls"
    mtlsSecretName: "fapi-pep-as-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-as-tls-cert"
  fapiPepRs:
    mtlsCAGoogleSecretName: "fapi-pep-rs-mtls-ca-certs"
    mtlsCASecretName: "fapi-pep-rs-mtls-ca-certs"
    mtlsCertPrefix: "dev-rs-mtls"
    mtlsSecretName: "fapi-pep-rs-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-rs-tls-cert"
  testTrustedDirectory:
    mtlsCAGoogleSecretName: "test-trusted-directory-mtls-ca-certs"
    mtlsCASecretName: "test-trusted-directory-mtls-ca-certs"
    tlsCertPrefix: "dev"
    tlsSecretName: "test-trusted-directory-tls-cert"
ig:
  truststore:
    fileName: "ig-truststore.pem"
    googleSecretName: "ig-truststore-pem"
    secretName: "ig-truststore-pem"
  ob:
    signingKey:
      fileName: "ig-ob-signing-key.p12"
      googleSecretName: "ig-ob-signing-key"
      secretName: "ig-ob-signing-key"
  testTrustedDirectory:
    fileName: "test-trusted-directory-keystore.p12"
    googleSecretName: "test-trusted-directory-keystore"
    secretName: "test-trusted-directory-keystore"
rcs:
  signing:
    certPrefix: "rcs-signing"
    secretName: "rcs-signing"