
serviceAccount: default

externalCert:
  projectId: example-project
  secretName: sslcert
  certPrefix: dev

ig:
  truststore:
    secretName: ig-truststore-pem
    fileName: ig-truststore.pem
    googleSecretName: ig-truststore-pem
