---
cloud:
  id: "nightly-private-id"
  key: "nightly-private-key"

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  cloudType: "CDK"
  projectId: "example-project"
  sapigType: "core"

externalCert:
  fapiPepAs:
    mtlsCertPrefix: "dev-as-mtls"
    mtlsSecretName: "fapi-pep-as-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-as-tls-cert"
  fapiPepRs:
    mtlsCertPrefix: "dev-rs-mtls"
    mtlsSecretName: "fapi-pep-rs-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-rs-tls-cert"
  ob:
    signingkey:
      googleSecretName: "ig-ob-signing-key"
  testTrustedDirectory:
    mtlsCAGoogleSecretName: "test-trusted-directory-mtls-ca-certs"
    mtlsCASecretName: "test-trusted-directory-mtls-ca-certs"
    tlsCertPrefix: "dev"
    tlsSecretName: "test-trusted-directory-tls-cert"
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: "am-oauth2-ca-certs"

fapiPepAs:
  branch: "HEAD"
  configmap:
    amRealm: "alpha"
    asFQDN: "as-sapig.dev-cdk-core.forgerock.financial"
    asMtlsFQDN: "as-mtls.sapig.dev-cdk-core.forgerock.financial"
    baseFQDN: "dev-cdk-core.forgerock.financial"
    cloudType: "CDK"
    identityPlatformFQDN: "iam.dev-cdk-core.forgerock.financial"
    igOBASPSPSigningKid: "8rzhDR1TEWDVtb1iE6IZyTZ7r0E"
    sapigType: "core"
    testDirectoryFQDN: "test-trusted-directory.dev-cdk-core.forgerock.financial"
    identityDefaultUserAuthenticationService: "PasswordGrant"
    identityGoogleSecretStoreName: "ESV"
    identityGoogleSecretStoreOAuth2CACertsSecretName: "esv-sapig-core-am-oauth2-ca-certs"
    userObject: "user"
  deployment:
    image:
      repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/fapi-pep-as"
      tag: "latest"
  ingress:
    asMtls:
      host: "as-mtls.sapig.dev-cdk-ob.forgerock.financial"
      tls:
        host: "as-mtls.sapig.dev-cdk-ob.forgerock.financial"
    asSapig:
      host: "as-sapig.dev-cdk-ob.forgerock.financial"
      tls:
        host: "as-sapig.dev-cdk-ob.forgerock.financial"
    asIGSstudio:
      host: "as-sapig.dev-cdk-ob.forgerock.financial"
      tls:
        host: "as-sapig.dev-cdk-ob.forgerock.financial"
  secrets:
    igAgentID: "aWctYWdlbnQ="
    igAgentPassword: "cGFzc3dvcmQ="
    igClientID: "aWctY2xpZW50"
    igClientSecret: "cGFzc3dvcmQ="
    igAsIdmClientSecret: "MHBlbkJhbmtpbmch"
    igRsIdmClientSecret: "T3BlbkJhbmtpbmchCg=="
    igMetricsPassword: "cGFzc3dvcmQ="
    igMetricsUsername: "dXNlcg=="
    igTruststorePassword: "Y2hhbmdlaXQ="
    igOBASPSPSigningKeystoreKeypass: "cGFzc3dvcmQ="
    igOBASPSPSigningKeystoreStorepass: "cGFzc3dvcmQ="

fapiPepRs:
  branch: "HEAD"
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: "am-oauth2-ca-certs"
  ob:
    signingkey:
      googleSecretName: "ig-ob-signing-key"
  configmap:
    amRealm: "alpha"
    asFQDN: "as-sapig.dev-cdk-core.forgerock.financial"
    baseFQDN: "dev-cdk-core.forgerock.financial"
    cloudType: "CDK"
    identityPlatformFQDN: "iam.dev-cdk-core.forgerock.financial"
    rsFQDN: "rs-sapig.dev-cdk-core.forgerock.financial"
    rsMtlsFQDN: "rs-mtls.sapig.dev-cdk-core.forgerock.financial"
    sapigType: "core"
    testDirectoryFQDN: "test-trusted-directory.dev-cdk-core.forgerock.financial"
    userObject: "user"
    identityDefaultUserAuthenticationService: "PasswordGrant"
    identityGoogleSecretStoreName: "ESV"
    identityGoogleSecretStoreOAuth2CACertsSecretName: "esv-sapig-core-am-oauth2-ca-certs"
  deployment:
    image:
      repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/fapi-pep-rs-core"
      tag: "latest"
  ingress:
    rsMtls:
      host: "rs-mtls.sapig.dev-cdk-ob.forgerock.financial"
      tls:
        host: "rs-mtls.sapig.dev-cdk-ob.forgerock.financial"
    rsSapig:
      host: "rs-sapig.dev-cdk-ob.forgerock.financial"
      tls:
        host: "rs-sapig.dev-cdk-ob.forgerock.financial"
    rsIGSstudio:
      host: "rs-sapig.dev-cdk-ob.forgerock.financial"
      tls:
        host: "rs-sapig.dev-cdk-ob.forgerock.financial"
  secrets:
    igAgentID: "aWctYWdlbnQ="
    igAgentPassword: "cGFzc3dvcmQ="
    igClientID: "aWctY2xpZW50"
    igClientSecret: "cGFzc3dvcmQ="
    igIDMPassword: "MHBlbkJhbmtpbmch"
    igIDMUser: "c2VydmljZV9hY2NvdW50Lmln"
    igMetricsPassword: "cGFzc3dvcmQ="
    igMetricsUsername: "dXNlcg=="
    igTruststorePassword: "Y2hhbmdlaXQ="

fidcConfigurator:
  enabled: "true"
  branch: "HEAD"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/secureopenbanking-uk-iam-initializer"
    tag: "latest"

spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "dev"
  source:
    targetRevision: "HEAD"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

testUserAccountCreator:
  branch: "HEAD"
  deployment:
    type: "Job"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-test-data-initializer"
    tag: "latest"

testTrustedDirectory:
  branch: "HEAD"
  configmap:
    igTestDirectoryFQDN: "test-trusted-directory.dev-cdk-core.forgerock.financial"
  deployment:
    image:
      repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/sapig-test-trusted-directory"
      tag: "latest"
  ingress:
    host: "test-trusted-directory.dev-cdk-core.forgerock.financial"
    tls:
      host: "test-trusted-directory.dev-cdk-core.forgerock.financial"
  secrets:
    igMetricsPassword: "dXNlcg=="
    igMetricsUsername: "cGFzc3dvcmQ="
    igTestDirectoryCAKeystoreKeypass: "UGFzc3cwcmQ="
    igTestDirectoryCAKeystoreStorepass: "UGFzc3cwcmQ="
    igTestDirectorySigningKeystoreKeypass: "UGFzc3cwcmQ="
    igTestDirectorySigningKeystoreStorepass: "UGFzc3cwcmQ="
