---
cloud:
  id: "nightly-private-id"
  key: "nightly-private-key"

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  cloudType: "CDK"
  projectId: "example-project"
  sapigType: "core"

externalCert:
  fapiPepAs:
    mtlsCertPrefix: "dev-as-mtls"
    mtlsSecretName: "fapi-pep-as-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-as-tls-cert"
  fapiPepRs:
    mtlsCertPrefix: "dev-rs-mtls"
    mtlsSecretName: "fapi-pep-rs-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-rs-tls-cert"
  sampleTrustedDirectory:
    mtlsCAGoogleSecretName: "sample-trusted-directory-mtls-ca-certs"
    mtlsCASecretName: "sample-trusted-directory-mtls-ca-certs"
    tlsCertPrefix: "dev"
    tlsSecretName: "sample-trusted-directory-tls-cert"
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: "am-oauth2-ca-certs"

fapiPepAs:
  repoURL: "https://github.com/ping-rocks/openig.git"
  branch: "HEAD"
  authorizationServer:
    realm: "alpha"
    fqdn: "as-sapig.dev-cdk-core.forgerock.financial"
    mtlsFqdn: "as-mtls.sapig.dev-cdk-core.forgerock.financial"
    baseFqdn: "dev-cdk-core.forgerock.financial"
  identityPlatform:
    fqdn: "iam.dev-cdk-core.forgerock.financial"
    googleSecretStoreProject: "sbat-gcr-develop"
  aic:
    identityDefaultUserAuthenticationService: "PasswordGrant"
    identityGoogleSecretStoreName: "ESV"
    identityGoogleSecretStoreOAuth2CACertsSecretName: "esv-sapig-core-am-oauth2-ca-certs"
  deployment:
    image:
      repo: "gcr.io/forgerock-io/ig-fapi-pep-as/docker-build"
      tag: "latest"
  pingGateway:
    oauth2Client:
      id: "aWctY2xpZW50"
      secret: "cGFzc3dvcmQ="
    idm:
      user: "c2VydmljZV9hY2NvdW50Lmln"
      password: "MHBlbkJhbmtpbmch"

fapiPepRs:
  repoURL: "https://github.com/ping-rocks/openig.git"
  branch: "HEAD"
  authorizationServer:
    realm: "alpha"
    fqdn: "as-sapig.dev-cdk-core.forgerock.financial"
    baseFqdn: "dev-cdk-core.forgerock.financial"
  identityPlatform:
    fqdn: "iam.dev-cdk-core.forgerock.financial"
    type: "CDK"
    userObject: "user"
  resourceServer:
    fqdn: "rs-sapig.dev-cdk-core.forgerock.financial"
    mtlsFqdn: "rs-mtls.sapig.dev-cdk-core.forgerock.financial"
    gatewayDataRepoUri: "http://ig:80"
    oauth2Client:
      id: "aWctY2xpZW50"
      secret: "cGFzc3dvcmQ="
    idm:
      user: "c2VydmljZV9hY2NvdW50Lmln"
      password: "MHBlbkJhbmtpbmch"
  aic:
    identityDefaultUserAuthenticationService: "PasswordGrant"
    identityGoogleSecretStoreName: "ESV"
    identityGoogleSecretStoreOAuth2CACertsSecretName: "esv-sapig-core-am-oauth2-ca-certs"
  deployment:
    image:
      repo: "gcr.io/forgerock-io/ig-fapi-pep-rs/docker-build"
      tag: "latest"
  ingress:
    mtls:
      serverCertSecret: "fapi-pep-rs-mtls-tls-cert"
      clientCaSecret: "fapi-pep-rs-mtls-ca-certs"
    tls:
      serverCertSecret: "fapi-pep-rs-tls-cert"

fidcConfigurator:
  enabled: "true"
  branch: "HEAD"
  asDeploymentConfigMap: "ig-fapi-pep-as-config"
  rsDeploymentConfigMap: "ig-fapi-pep-rs-config"
  asSecret: "ig-fapi-pep-as-secrets"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/secureopenbanking-uk-iam-initializer"
    tag: "latest"

spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "dev"
  source:
    targetRevision: "HEAD"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

testUserAccountCreator:
  branch: "HEAD"
  asDeploymentConfigMap: "ig-fapi-pep-as-config"
  deployment:
    type: "Job"
  image:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-test-data-initializer"
    tag: "latest"

sampleTrustedDirectory:
  branch: "HEAD"
  config:
    fqdn: "test-trusted-directory.dev-cdk-core.forgerock.financial"
    ca:
      keystorePwd: "UGFzc3cwcmQ="
      keystoreKeyPwd: "UGFzc3cwcmQ="
    signing:
      keystorePwd: "UGFzc3cwcmQ="
      keystoreKeyPwd: "UGFzc3cwcmQ="
  deployment:
    image:
      repo: "gcr.io/forgerock-io/ig-sample-trusted-directory/docker-build"
      tag: "latest"
  ingress:
    host: "test-trusted-directory.dev-cdk-core.forgerock.financial"
    tls:
      host: "test-trusted-directory.dev-cdk-core.forgerock.financial"