---
cloud:
  id: nightly-private-id
  key: nightly-private-key

cors:
  originEnds: localhost

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  cloudType: CDK
  sapigType: core
  kustomizeFolder: dev

externalCert:
  projectId: example-project
  fapiPepAS:
    mtlsSecretName: fapi-pep-as-mtls-tls-cert
    mtlsCertPrefix: dev-as-mtls
    tlsSecretName: fapi-pep-as-tls-cert
    tlsCertPrefix: dev
  fapiPepRS:
    mtlsSecretName: fapi-pep-rs-mtls-tls-cert
    mtlsCertPrefix: dev-rs-mtls
    tlsSecretName: fapi-pep-rs-tls-cert
    tlsCertPrefix: dev
  testTrustedDirectory:
    tlsSecretName: ttd-tls-cert
    tlsCertPrefix: dev

fidcConfigurator:
  enabled: true
  branch: HEAD
  repo: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/secureopenbanking-uk-iam-initializer
  tag: latest

devenvs:
  fapiPepAS:
    tag: latest
    branch: master
    truststore:
      # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
      googleSecretName: am-oauth2-ca-certs
    ob:
      signingkey:
        googleSecretName: ig-ob-signing-key
  fapiPepRS:
    tag: latest
    branch: master
    truststore:
      # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
      googleSecretName: am-oauth2-ca-certs
    ob:
      signingkey:
        googleSecretName: ig-ob-signing-key

ingress:
  domain: localhost

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

testUserAccountCreator:
  branch: HEAD
  deployment:
    type: Job
  repo: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-test-data-initializer
  tag: latest

testTrustedDirectory:
  branch: 1679-use-helm-to-install
  configmap:
    igTestDirectoryFQDN: test-trusted-directory.-wmorrison365fr-core.forgerock.financial
  deployment:
    repo: europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/sapig-test-trusted-directory
    tag: latest
  ingress:
    host: test-trusted-directory.-wmorrison365fr-core.forgerock.financial
    tls:
      host: test-trusted-directory.-wmorrison365fr-core.forgerock.financial
  secrets:
    igMetricsPassword: "dXNlcg=="
    igMetricsUsername: "cGFzc3dvcmQ="
    igTestDirectoryCAKeystoreKeypass: "UGFzc3cwcmQ="
    igTestDirectoryCAKeystoreStorepass: "UGFzc3cwcmQ="
    igTestDirectorySigningKeystoreKeypass: "UGFzc3cwcmQ="
    igTestDirectorySigningKeystoreStorepass: "UGFzc3cwcmQ="
