---
cloud:
  id: "nightly-private-id"
  key: "nightly-private-key"

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  cloudType: "CDK"
  projectId: "example-project"
  sapigType: "core"

externalCert:
  fapiPepAS:
    mtlsCertPrefix: "dev-as-mtls"
    mtlsSecretName: "fapi-pep-as-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-as-tls-cert"
  fapiPepRS:
    mtlsCertPrefix: "dev-rs-mtls"
    mtlsSecretName: "fapi-pep-rs-mtls-tls-cert"
    tlsCertPrefix: "dev"
    tlsSecretName: "fapi-pep-rs-tls-cert"
  testTrustedDirectory:
    mtlsCAGoogleSecretName: "test-trusted-directory-mtls-ca-certs"
    mtlsCASecretName: "test-trusted-directory-mtls-ca-certs"
    tlsCertPrefix: "dev"
    tlsSecretName: "test-trusted-directory-tls-cert"

fidcConfigurator:
  enabled: "true"
  branch: "HEAD"
  repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/secureopenbanking-uk-iam-initializer"
  tag: "latest"

devenvs:
  fapiPepAS:
    tag: "latest"
    branch: "master"
    truststore:
      # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
      googleSecretName: "am-oauth2-ca-certs"
    ob:
      signingkey:
        googleSecretName: "ig-ob-signing-key"
  fapiPepRS:
    tag: "latest"
    branch: "master"
    truststore:
      # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
      googleSecretName: "am-oauth2-ca-certs"
    ob:
      signingkey:
        googleSecretName: "ig-ob-signing-key"

spec:
  project: "default"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "dev"
  source:
    # SH - REVERT TO HEAD
    targetRevision: "1679-use-helm-to-install"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

testUserAccountCreator:
  branch: "HEAD"
  deployment:
    type: "Job"
  repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/securebanking-test-data-initializer"
  tag: "latest"

testTrustedDirectory:
  # SH - REVERT TO HEAD
  branch: "1679-use-helm-to-install"
  configmap:
    igTestDirectoryFQDN: "test-trusted-directory.dev-cdk-core.forgerock.financial"
  deployment:
    repo: "europe-west4-docker.pkg.dev/sbat-gcr-develop/sapig-docker-artifact/securebanking/sapig-test-trusted-directory"
    tag: "latest"
  ingress:
    host: "test-trusted-directory.dev-cdk-core.forgerock.financial"
    tls:
      host: "test-trusted-directory.dev-cdk-core.forgerock.financial"
  secrets:
    igMetricsPassword: "dXNlcg=="
    igMetricsUsername: "cGFzc3dvcmQ="
    igTestDirectoryCAKeystoreKeypass: "UGFzc3cwcmQ="
    igTestDirectoryCAKeystoreStorepass: "UGFzc3cwcmQ="
    igTestDirectorySigningKeystoreKeypass: "UGFzc3cwcmQ="
    igTestDirectorySigningKeystoreStorepass: "UGFzc3cwcmQ="
