apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fapi-pep-rs-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # Authorization Server
        - name: authorizationServer.realm
          value: {{ .Values.fapiPepRs.authorizationServer.realm }}
        - name: authorizationServer.fqdn
          value: {{ .Values.fapiPepRs.authorizationServer.fqdn }}
        - name: authorizationServer.baseFqdn
          value: {{ .Values.fapiPepRs.authorizationServer.baseFqdn }}
        # Identity Platform
        - name: identityPlatform.fqdn
          value: {{ .Values.fapiPepRs.identityPlatform.fqdn }}
        - name: identityPlatform.type
          value: {{ .Values.fapiPepRs.identityPlatform.type }}
        # Resource Server
        - name: resourceServer.fqdn
          value: {{ .Values.fapiPepRs.resourceServer.fqdn }}
        - name: resourceServer.mtlsFqdn
          value: {{ .Values.fapiPepRs.resourceServer.mtlsFqdn }}
        - name: resourceServer.userObject
          value: {{ .Values.fapiPepRs.resourceServer.userObject }}
        - name: resourceServer.oauth2Client.id
          value: {{ .Values.fapiPepRs.resourceServer.oauth2Client.id }}
        - name: resourceServer.oauth2Client.secret
          value: {{ .Values.fapiPepRs.resourceServer.oauth2Client.secret }}
        - name: resourceServer.idm.user
          value: {{ .Values.fapiPepRs.resourceServer.idm.user }}
        - name: resourceServer.idm.password
          value: {{ .Values.fapiPepRs.resourceServer.idm.password }}
        - name: resourceServer.agent.id
          value: {{ .Values.fapiPepRs.resourceServer.agent.id }}
        - name: resourceServer.agent.password
          value: {{ .Values.fapiPepRs.resourceServer.agent.password }}
        - name: resourceServer.ob.signingKeystore.kid
          value: {{ .Values.fapiPepRs.resourceServer.ob.signingKeystore.kid }}
        - name: resourceServer.ob.signingKeystore.storepass
          value: {{ .Values.fapiPepRs.resourceServer.ob.signingKeystore.storepass }}
        - name: resourceServer.ob.signingKeystore.keypass
          value: {{ .Values.fapiPepRs.resourceServer.ob.signingKeystore.keypass }}
        # MongoDB
        - name: mongodb.testFacility.username
          value: {{ .Values.fapiPepRs.mongodb.testFacility.username }}
        - name: mongodb.testFacility.password
          value: {{ .Values.fapiPepRs.mongodb.testFacility.password }}
        - name: mongodb.consent.username
          value: {{ .Values.fapiPepRs.mongodb.consent.username }}
        - name: mongodb.consent.password
          value: {{ .Values.fapiPepRs.mongodb.consent.password }}
        # AIC
        - name: aic.identityDefaultUserAuthenticationService
          value: {{ .Values.fapiPepRs.aic.identityDefaultUserAuthenticationService }}
        - name: aic.identityGoogleSecretStoreName
          value: {{ .Values.fapiPepRs.aic.identityGoogleSecretStoreName }}
        - name: aic.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.fapiPepRs.aic.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: deployment.image.repo
          value: {{ .Values.fapiPepRs.deployment.image.repo}}
        - name: deployment.image.tag
          value: {{ .Values.fapiPepRs.deployment.image.tag }}
        # Ingress
        - name: ingress.mtls.serverCertSecret
          value: {{ .Values.fapiPepRs.ingress.mtls.serverCertSecret }}
        - name: ingress.mtls.clientCaSecret
          value: {{ .Values.fapiPepRs.ingress.mtls.clientCaSecret }}
        - name: ingress.tls.serverCertSecret
          value: {{ .Values.fapiPepRs.ingress.tls.serverCertSecret }}
    path: _infra/helm/secure-api-gateway-fapi-pep-rs-ob
    repoURL: https://github.com/SecureApiGateway/secure-api-gateway-fapi-pep-rs-ob
    targetRevision: {{ .Values.fapiPepRs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
