apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fapi-pep-rs-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # ConfigMap
        - name: configmap.amRealm
          value: {{ .Values.fapiPepRs.configmap.amRealm }}
        - name: configmap.baseFQDN
          value: {{ .Values.fapiPepRs.configmap.baseFQDN }}
        - name: configmap.cloudType
          value: {{ .Values.fapiPepRs.configmap.cloudType }}
        - name: configmap.identityPlatformFQDN
          value: {{ .Values.fapiPepRs.configmap.identityPlatformFQDN }}
        - name: configmap.asFQDN
          value: {{ .Values.fapiPepRs.configmap.asFQDN }}
        - name: configmap.rsFQDN
          value: {{ .Values.fapiPepRs.configmap.rsFQDN }}
        - name: configmap.rsMtlsFQDN
          value: {{ .Values.fapiPepRs.configmap.rsMtlsFQDN }}
        - name: configmap.sapigType
          value: {{ .Values.fapiPepRs.configmap.sapigType }}
        - name: configmap.testDirectoryFQDN
          value: {{ .Values.fapiPepRs.configmap.testDirectoryFQDN }}
        - name: configmap.userObject
          value: {{ .Values.fapiPepRs.configmap.userObject }}
        - name: configmap.AIC.identityDefaultUserAuthenticationService
          value: {{ .Values.fapiPepRs.configmap.identityDefaultUserAuthenticationService }}
        - name: configmap.AIC.identityGoogleSecretStoreName
          value: {{ .Values.fapiPepRs.configmap.identityGoogleSecretStoreName }}
        - name: configmap.AIC.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.fapiPepRs.configmap.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: deployment.image.repo
          value: {{ .Values.fapiPepRs.deployment.image.repo}}
        - name: deployment.image.tag
          value: {{ .Values.fapiPepRs.deployment.image.tag }}
        # Ingress
        - name: ingress.rsSapig.host
          value: {{ .Values.fapiPepRs.ingress.rsSapig.host }}
        - name: ingress.rsSapig.tls.host
          value: {{ .Values.fapiPepRs.ingress.rsSapig.tls.host }}
        - name: ingress.rsMtls.host
          value: {{ .Values.fapiPepRs.ingress.rsMtls.host }}
        - name: ingress.rsMtls.tls.host
          value: {{ .Values.fapiPepRs.ingress.rsMtls.tls.host }}
        - name: ingress.rsIGSstudio.host
          value: {{ .Values.fapiPepRs.ingress.rsIGSstudio.host }}
        - name: ingress.rsIGSstudio.tls.host
          value: {{ .Values.fapiPepRs.ingress.rsIGSstudio.tls.host }}
        # Secrets
        - name: secrets.igAgentID
          value: {{ .Values.fapiPepRs.secrets.igAgentID }}
        - name: secrets.igAgentPassword
          value: {{ .Values.fapiPepRs.secrets.igAgentPassword }}
        - name: secrets.igClientID
          value: {{ .Values.fapiPepRs.secrets.igClientID }}
        - name: secrets.igClientSecret
          value: {{ .Values.fapiPepRs.secrets.igClientSecret }}
        - name: secrets.igAsIdmClientSecret
          value: {{ .Values.fapiPepRs.secrets.igAsIdmClientSecret }}
        - name: secrets.igRsIdmClientSecret
          value: {{ .Values.fapiPepRs.secrets.igRsIdmClientSecret }}
        - name: secrets.igMetricsPassword
          value: {{ .Values.fapiPepRs.secrets.igMetricsPassword }}
        - name: secrets.igMetricsUsername
          value: {{ .Values.fapiPepRs.secrets.igMetricsUsername }}
        - name: secrets.igOBASPSPSigningKeystoreKeypass
          value: {{ .Values.fapiPepRs.secrets.igOBASPSPSigningKeystoreKeypass }}
        - name: secrets.igOBASPSPSigningKeystoreStorepass
          value: {{ .Values.fapiPepRs.secrets.igOBASPSPSigningKeystoreStorepass }}
        - name: secrets.igTruststorePassword
          value: {{ .Values.fapiPepRs.secrets.igTruststorePassword }}
        - name: secrets.mongodbConsentPassword
          value: {{ .Values.fapiPepRs.secrets.mongodbConsentPassword }}
        - name: secrets.mongodbConsentUsername
          value: {{ .Values.fapiPepRs.secrets.mongodbConsentUsername }}
        - name: secrets.mongodbTestFacilityPassword
          value: {{ .Values.fapiPepRs.secrets.mongodbTestFacilityPassword }}
        - name: secrets.mongodbTestFacilityUsername
          value: {{ .Values.fapiPepRs.secrets.mongodbTestFacilityUsername }}
    path: _infra/helm/secure-api-gateway-fapi-pep-rs-ob
    repoURL: https://github.com/SecureApiGateway/secure-api-gateway-fapi-pep-rs-ob
    targetRevision: {{ .Values.fapiPepRs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
