apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fapi-pep-as-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # Authorization Server
        - name: authorizationServer.realm
          value: {{ .Values.fapiPepAs.authorizationServer.realm }}
        - name: authorizationServer.fqdn
          value: {{ .Values.fapiPepAs.authorizationServer.fqdn }}
        - name: authorizationServer.mtlsFqdn
          value: {{ .Values.fapiPepAs.authorizationServer.mtlsFqdn }}
        - name: authorizationServer.baseFqdn
          value: {{ .Values.fapiPepAs.authorizationServer.baseFqdn }}
        # Identity Platform
        - name: identityPlatform.fqdn
          value: {{ .Values.fapiPepAs.identityPlatform.fqdn }}
        - name: identityPlatform.type
          value: {{ .Values.fapiPepAs.identityPlatform.type }}
        - name: identityPlatform.googleSecretStoreProject
          value: {{ .Values.fapiPepAs.identityPlatform.googleSecretStoreProject }}
        # Test Directory
        - name: testDirectory.fqdn
          value: {{ .Values.sampleTrustedDirectory.config.fqdn }}
        # AIC
        - name: aic.identityDefaultUserAuthenticationService
          value: {{ .Values.fapiPepAs.aic.identityDefaultUserAuthenticationService }}
        - name: aic.identityGoogleSecretStoreName
          value: {{ .Values.fapiPepAs.aic.identityGoogleSecretStoreName }}
        - name: aic.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.fapiPepAs.aic.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: deployment.image.repo
          value: {{ .Values.fapiPepAs.deployment.image.repo }}
        - name: deployment.image.tag
          value: {{ .Values.fapiPepAs.deployment.image.tag }}
        # Secrets
        - name: pingGateway.oauth2Client.id
          value: {{ .Values.fapiPepAs.pingGateway.oauth2Client.id }}
        - name: pingGateway.oauth2Client.secret
          value: {{ .Values.fapiPepAs.pingGateway.oauth2Client.secret }}
        - name: pingGateway.idm.user
          value: {{ .Values.fapiPepAs.pingGateway.idm.user }}
        - name: pingGateway.idm.password
          value: {{ .Values.fapiPepAs.pingGateway.idm.password }}
    path: openig-helm/ig-fapi-pep-as
    repoURL: {{ .Values.fapiPepAs.repoURL }}
    targetRevision: {{ .Values.fapiPepAs.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
