apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ig-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        # ConfigMap
        - name: configmap.amRealm
          value: {{ .Values.ob.configmap.amRealm }}
        - name: configmap.baseFQDN
          value: {{ .Values.ob.configmap.baseFQDN }}
        - name: configmap.cloudType
          value: {{ .Values.ob.configmap.cloudType }}
        - name: configmap.identityPlatformFQDN
          value: {{ .Values.ob.configmap.identityPlatformFQDN }}
        - name: configmap.igFQDN
          value: {{ .Values.ob.configmap.igFQDN }}
        - name: configmap.mtlsFQDN
          value: {{ .Values.ob.configmap.mtlsFQDN }}
        - name: configmap.sapigType
          value: {{ .Values.ob.configmap.sapigType }}
        - name: configmap.testDirectoryFQDN
          value: {{ .Values.ob.configmap.testDirectoryFQDN }}
        - name: configmap.AIC.identityDefaultUserAuthenticationService
          value: {{ .Values.ob.configmap.identityDefaultUserAuthenticationService }}
        - name: configmap.AIC.identityGoogleSecretStoreName
          value: {{ .Values.ob.configmap.identityGoogleSecretStoreName }}
        - name: configmap.AIC.identityGoogleSecretStoreOAuth2CACertsSecretName
          value: {{ .Values.ob.configmap.identityGoogleSecretStoreOAuth2CACertsSecretName }}
        # Deployment
        - name: deployment.image.repo
          value: {{ .Values.ob.deployment.repo}}
        - name: deployment.image.tag
          value: {{ .Values.ob.deployment.tag }}
        # Ingress
        - name: ingress.sapig.host
          value: {{ .Values.ob.ingress.sapig.host }}
        - name: ingress.sapig.tls.host
          value: {{ .Values.ob.ingress.sapig.tls.host }}
        - name: ingress.mtls.host
          value: {{ .Values.ob.ingress.mtls.host }}
        - name: ingress.mtls.tls.host
          value: {{ .Values.ob.ingress.mtls.tls.host }}
        - name: ingress.igWeb.host
          value: {{ .Values.ob.ingress.igWeb.host }}
        - name: ingress.igWeb.tls.host
          value: {{ .Values.ob.ingress.igWeb.tls.host }}
        # Secrets
        - name: secrets.igAgentID
          value: {{ .Values.ob.secrets.igAgentID }}
        - name: secrets.igAgentPassword
          value: {{ .Values.ob.secrets.igAgentPassword }}
        - name: secrets.igClientID
          value: {{ .Values.ob.secrets.igClientID }}
        - name: secrets.igClientSecret
          value: {{ .Values.ob.secrets.igClientSecret }}
        - name: secrets.igIDMPassword
          value: {{ .Values.ob.secrets.igIDMPassword }}
        - name: secrets.igIDMUser
          value: {{ .Values.ob.secrets.igIDMUser }}
        - name: secrets.igMetricsPassword
          value: {{ .Values.ob.secrets.igMetricsPassword }}
        - name: secrets.igMetricsUsername
          value: {{ .Values.ob.secrets.igMetricsUsername }}
        - name: secrets.igOBASPSPSigningKeystoreKeypass
          value: {{ .Values.ob.secrets.igOBASPSPSigningKeystoreKeypass }}
        - name: secrets.igOBASPSPSigningKeystoreStorepass
          value: {{ .Values.ob.secrets.igOBASPSPSigningKeystoreStorepass }}
        - name: secrets.igTruststorePassword
          value: {{ .Values.ob.secrets.igTruststorePassword }}
        - name: secrets.mongodbConsentPassword
          value: {{ .Values.ob.secrets.mongodbConsentPassword }}
        - name: secrets.mongodbConsentUsername
          value: {{ .Values.ob.secrets.mongodbConsentUsername }}
        - name: secrets.mongodbTestFacilityPassword
          value: {{ .Values.ob.secrets.mongodbTestFacilityPassword }}
        - name: secrets.mongodbTestFacilityUsername
          value: {{ .Values.ob.secrets.mongodbTestFacilityUsername }}
    path: _infra/helm/secure-api-gateway-ob-uk
    repoURL: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk
    targetRevision: {{ .Values.ob.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
