apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-setup-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: cloud.key
          value: {{ .Values.cloud.key }}
        - name: cloud.id
          value: {{ .Values.cloud.id }}
        - name: environment.cloudType
          value: {{ .Values.environment.cloudType }}
        - name: environment.projectId
          value: {{ .Values.environment.projectId }}
        - name: environment.sapigType
          value: {{ .Values.environment.sapigType }}
        - name: externalCert.fapiPepAs.mtlsCertPrefix
          value: {{ .Values.externalCert.fapiPepAs.mtlsCertPrefix }}
        - name: externalCert.fapiPepRs.mtlsCertPrefix
          value: {{ .Values.externalCert.fapiPepRs.mtlsCertPrefix }}
        - name: externalCert.fapiPepAs.tlsCertPrefix
          value: {{ .Values.externalCert.fapiPepAs.tlsCertPrefix }}
        - name: externalCert.fapiPepRs.tlsCertPrefix
          value: {{ .Values.externalCert.fapiPepRs.tlsCertPrefix }}
        - name: externalCert.testTrustedDirectory.tlsCertPrefix
          value: {{ .Values.externalCert.testTrustedDirectory.tlsCertPrefix }}
        - name: ig.truststore.googleSecretName
          value: {{ .Values.externalCert.truststore.googleSecretName }}
        - name: ig.ob.signingkey.googleSecretName
          value: {{ .Values.externalCert.ob.signingkey.googleSecretName }}
    path: cluster/certificate
    repoURL: https://github.com/SecureBankingAccessToolkit/sbat-cd
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true