apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: remote-consent-server-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: deployment.image.repo
        value: {{ .Values.remoteConsentServer.image.repo }}
      - name: deployment.image.tag
        value: {{ .Values.remoteConsentServer.image.tag }}
      - name: deployment.mongodb.host
        value: "mongodb-{{ .Release.Name }}"
    path: _infra/helm/securebanking-openbanking-uk-rcs
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs
    targetRevision: {{ .Values.remoteConsentServer.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}
