apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-facility-bank-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
      - name: deployment.mongodb.host
        value: "mongodb-{{ .Release.Name }}"
      - name: deployment.image.repo
        value: {{ .Values.testFacilityBank.image.repo }}
      - name: deployment.image.tag
        value: {{ .Values.testFacilityBank.image.tag }}
      values: |
        configmap:
          springConfig:
            testdata:
              userAccountIds:
                psu4test:
                  - sortCode: "012332"
                    accountNumber: "43245676"
                  - sortCode: "012332"
                    accountNumber: "54312390"
                  - sortCode: "334412"
                    accountNumber: "30187862"
            rs:
              data:
                customerInfo:
                  enabled: true
              discovery:
                versions:
                  v3.0: false
                  v3.1: false
                  v3.1.1: false
                  v3.1.2: false
                  v3.1.3: false
                  v3.1.4: false
                  v3.1.5: false
                  v3.1.6: false
                  v3.1.7: false
                  v3.1.8: false
                  v3.1.9: false
                  v3.1.10: true
                  v4.0.0: true
                apis:
                  # These APIs are not currently implemented
                  CREATE_CALLBACK_URL: false
                  GET_CALLBACK_URLS: false
                  AMEND_CALLBACK_URL: false
                  DELETE_CALLBACK_URL: false

    path: _infra/helm/securebanking-openbanking-uk-rs
    repoURL: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs
    targetRevision: {{ .Values.testFacilityBank.branch }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 4 }}