spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    targetRevision: fix-quote

ingress:
  domain: localhost

externalCert:
  projectId: example-project
  defaultWildcard: true
