spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    targetRevision: HEAD

config:
  domain: localhost

securebanking-rcs-dev:
  deployment:
    imageOverride:
      tag: test-pr
      
tag:
  ui:
    auth: latest
    rcs: latest
    swagger: latest
  api:
    rcs: latest
    rs: latest

externalCert:
  projectId: example-project
