apiVersion: batch/v1
kind: Job
metadata:
  name: apply-gcr-secret-to-sa
  annotations:
    "helm.sh/hook": post-install
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      serviceAccountName: job-sa
      restartPolicy: Never
      containers:
        - name: gcloud
          image: google/cloud-sdk
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              kubectl patch sa {{ .Values.serviceAccount }} -p '{"metadata":{"annotations":{"iam.gke.io/gcp-service-account": "sbat-master-dev-gcr@{{ .Values.externalCert.projectId }}.iam.gserviceaccount.com"}}}'
