use:
  fidc: "true"
    initializer: "true"

urls:
  ig:
    server: https://obdemo.nightly.forgerock.financial
  rcsUI:
    server: https://rcs-ui.nightly.forgerock.financial
  rcs:
    server: https://rcs.nightly.forgerock.financial
  rs:
    server: https://rs.nightly.forgerock.financial
  swaggerUI:
    server: https://swagger.nightly.forgerock.financial
  swagger:
    json: localhost

cors:
  originEnds: nightly.forgerock.financial
