spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: HEAD

  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

ingress:
  domain: localhost

cors:
  originEnds: localhost

rcs:
  tag: latest
  branch: HEAD

rs:
  tag: latest
  branch: HEAD

ui:
  tag: latest
  branch: HEAD
  templateName: forgerock

ig:
  tag: latest
  branch: HEAD
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: am-oauth2-ca-certs

iamInitialiser:
  tag: latest
  branch: HEAD

iamSecretManager:
  tag: latest
  branch: HEAD

testUserInit:
  tag: latest
  branch: HEAD
  deploymentType: CronJob

mongodb:
  auth:
    enabled: false

externalCert:
  projectId: example-project
  secretName: sslcert
  certPrefix: dev

openBankingCert:
  certPrefix: dev-ob-wac

# environment.type: It can be:
# CDK value: (Cloud Developer's Kit) development identity platform
# CDM value: CDM (Cloud Deployment Model) identity cloud platform
# FIDC value: Cloud Deployment Model) identity cloud platform
environment:
  type: CDK
