spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/SecureBankingAccessToolkit/init-charts
    targetRevision: HEAD

  syncPolicy: {}

config:
  domain: localhost
  externalCert:
    projectId: example-project
