spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: HEAD

  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

ingress:
  domain: localhost

cors:
  originEnds: localhost

config:
  tag: latest
  branch: HEAD

rcs:
  tag: latest
  branch: HEAD

rs:
  tag: latest
  branch: HEAD

ui:
  tag: latest
  branch: HEAD
  # Pod env default values (overwritten in ./environments/values-${namespace}.yaml)
  templateName: forgerock

ig:
  tag: latest
  branch: HEAD

mongodb:
  auth:
    enabled: false

externalCert:
  projectId: example-project

use:
  fidc: "false"
    initializer: "false"

urls:
  ig:
    server: https://obdemo.dev.forgerock.financial
  authorization:
    server: https://iam.dev.forgerock.financial
  rcsUI:
    server: https://rcs-ui.dev.forgerock.financial
  rcs:
    server: https://rcs.dev.forgerock.financial
  rs:
    server: https://rs.dev.forgerock.financial
  swaggerUI:
    server: https://swagger.dev.forgerock.financial
  swagger:
    json: localhost
