---
cors:
  originEnds: localhost

environment:
  # CDK value: (Cloud Developer's Kit) development identity platform
  # CDM value: CDM (Cloud Deployment Model) identity cloud platform
  # FIDC value: Cloud Deployment Model) identity cloud platform
  type: CDK

externalCert:
  projectId: example-project
  secretName: sslcert
  certPrefix: dev

fidcConfigurator:
  branch: HEAD
  repo: eu.gcr.io/sbat-gcr-develop/securebanking/secureopenbanking-uk-iam-initializer
  tag: latest

iamSecretManager:
  tag: latest
  branch: HEAD

ig:
  tag: latest
  branch: HEAD
  truststore:
    # Reusing the secret that configures AM to trust CAs for OAuth 2.0 tls_client_auth
    googleSecretName: am-oauth2-ca-certs

ingress:
  domain: localhost

mongodb:
  auth:
    enabled: false

openBankingCert:
  certPrefix: dev-ob-wac

remoteConsentServer:
  branch: HEAD
  repo: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-openbanking-uk-rcs
  tag: latest
  replicas: "3"

remoteConsentServiceUserInterface:
  branch: HEAD
  repo: eu.gcr.io/sbat-gcr-develop/securebanking/ui/rcs
  tag: latest
  replicas: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true

testFacilityBank:
  branch: HEAD
  repo: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-openbanking-uk-rs
  tag: latest
  replicas: "3"

testUserAccountCreator:
  branch: HEAD
  deployment:
    type: CronJob
  repo: eu.gcr.io/sbat-gcr-develop/securebanking/securebanking-test-data-initializer
  tag: latest